name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        versions:
          - elixir: 1.15.0
            erlang: 24.0
          - elixir: 1.16.0
            erlang: 24.0
          - elixir: 1.17.0
            erlang: 27.1
          - elixir: 1.18.0
            erlang: 27.2
    name: Elixir v${{ matrix.versions.elixir }}, Erlang v${{ matrix.versions.erlang }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.versions.erlang}}
          elixir-version: ${{matrix.versions.elixir}}

      - uses: actions/cache@v3
        with:
          path: deps
          key: mix-deps-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get

      - run: mix format --check-formatted
        if: matrix.os != 'windows-latest'

      - run: mix deps.unlock --check-unused

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors

      - run: mix test --warnings-as-errors
